package com.codersfarm.subdomains.service;

import com.codersfarm.subdomains.dto.DnsRecordForm;
import com.codersfarm.subdomains.model.DnsRecord;
import com.codersfarm.subdomains.model.Subdomain;
import com.codersfarm.subdomains.repository.DnsRecordRepository;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.util.List;
import java.util.Optional;
import java.util.stream.Collectors;

@Service
public class DnsRecordService {

    private final DnsRecordRepository dnsRecordRepository;
    private final CloudflareService cloudflareService;
    private final SubdomainService subdomainService;

    @Value("${app.max-records-per-subdomain:20}")
    private int maxRecords;

    @Value("${app.base-domain:codersfarm.com}")
    private String baseDomain;

    public DnsRecordService(DnsRecordRepository dnsRecordRepository,
                            CloudflareService cloudflareService,
                            SubdomainService subdomainService) {
        this.dnsRecordRepository = dnsRecordRepository;
        this.cloudflareService = cloudflareService;
        this.subdomainService = subdomainService;
    }

    public List<DnsRecord> getRecords(Subdomain subdomain) {
        return dnsRecordRepository.findBySubdomainIdOrderByCreatedAtAsc(subdomain.getId());
    }

    @Transactional
    public DnsRecord addRecord(Subdomain subdomain, DnsRecordForm form) {
        int count = dnsRecordRepository.countBySubdomainId(subdomain.getId());
        if (count >= maxRecords) {
            throw new IllegalStateException("Maximum of " + maxRecords + " records per subdomain reached");
        }

        DnsRecord record = new DnsRecord();
        record.setSubdomain(subdomain);
        record.setRecordType(form.getRecordType());
        record.setName(buildRecordName(form.getName(), subdomain));
        record.setValue(form.getValue().trim());
        record.setTtl(form.getTtl());
        record.setPriority(form.getPriority());

        String providerRecordId = cloudflareService.createRecord(
                subdomain.getFullDomain(), record);
        record.setCloudflareRecordId(providerRecordId);
        record.setPropagationStatus("pending");

        subdomainService.touch(subdomain);
        return dnsRecordRepository.save(record);
    }

    @Transactional
    public DnsRecord updateRecord(Subdomain subdomain, Long recordId, DnsRecordForm form) {
        DnsRecord record = dnsRecordRepository.findById(recordId)
                .orElseThrow(() -> new IllegalArgumentException("Record not found"));

        if (!record.getSubdomain().getId().equals(subdomain.getId())) {
            throw new SecurityException("Record does not belong to your subdomain");
        }

        record.setRecordType(form.getRecordType());
        record.setName(buildRecordName(form.getName(), subdomain));
        record.setValue(form.getValue().trim());
        record.setTtl(form.getTtl());
        record.setPriority(form.getPriority());
        record.setPropagationStatus("pending");

        if (record.getCloudflareRecordId() != null) {
            cloudflareService.updateRecord(
                    subdomain.getFullDomain(), record.getCloudflareRecordId(), record);
        }

        subdomainService.touch(subdomain);
        return dnsRecordRepository.save(record);
    }

    @Transactional
    public void deleteRecord(Subdomain subdomain, Long recordId) {
        DnsRecord record = dnsRecordRepository.findById(recordId)
                .orElseThrow(() -> new IllegalArgumentException("Record not found"));

        if (!record.getSubdomain().getId().equals(subdomain.getId())) {
            throw new SecurityException("Record does not belong to your subdomain");
        }

        if (record.getCloudflareRecordId() != null) {
            cloudflareService.deleteRecord(
                    subdomain.getFullDomain(), record.getCloudflareRecordId());
        }

        dnsRecordRepository.delete(record);
        subdomainService.touch(subdomain);
    }

    public String generateZoneFile(Subdomain subdomain) {
        List<DnsRecord> records = getRecords(subdomain);
        StringBuilder sb = new StringBuilder();
        sb.append("; Zone file for ").append(subdomain.getFullDomain()).append("\n");
        sb.append("; Generated by Coders Farm DNS Manager\n");
        sb.append(";\n");
        sb.append(String.format("; %-28s %6s     %-5s %s%n", "NAME", "TTL", "TYPE", "VALUE"));
        sb.append("; ").append("-".repeat(70)).append("\n");

        for (DnsRecord record : records) {
            sb.append(record.toZoneLine()).append("\n");
        }

        return sb.toString();
    }

    public Optional<DnsRecord> findById(Long id) {
        return dnsRecordRepository.findById(id);
    }

    private String buildRecordName(String inputName, Subdomain subdomain) {
        String name = inputName.trim().toLowerCase();
        // If user enters "@" or empty, use the subdomain itself
        if (name.equals("@") || name.isEmpty()) {
            return subdomain.getFullDomain();
        }
        // If they already provided the full domain, keep it
        if (name.endsWith("." + baseDomain)) {
            return name;
        }
        // Otherwise, append .subdomain.baseDomain
        return name + "." + subdomain.getFullDomain();
    }
}
